language: node_js
branches:
  only:
    - master
    - /^greenkeeper.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # Allow vX.X.X tags
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      name: Lint code
      node_js: lts/*
      script:
        - yarn dev
        - yarn lint
        - yarn --cwd ./demo run lint
    - stage: test
      name: Run tests (Node.js Current)
      node_js: node
      script:
        - yarn dev
        - yarn test
    - stage: test
      name: Run tests (Node.js LTS)
      node_js: lts/*
      script:
        - yarn global add codecov
        - yarn dev
        - yarn test
        - codecov
    - stage: deploy
      if: type = push AND tag IS present
      name: Deploy to npm
      node_js: lts/*
      script:
        - yarn dev
        - yarn compile
        - echo "Deploying to npm..."
      deploy:
        provider: npm
        skip_cleanup: true
        email: wes@sparksuite.com
        api_key:
          secure: KjhT/uNlOgk4p2wz7mQEx8CSLE5x13VS3J4mYRZFQJe5AWBbKQi2UO1rxq95fHYGncw4BS+fr4ruZy+fzud29Z+gu/bKBDoIw6Hnz6s8rYKYtb2HBE8vcZ9Lf/wq/Epp/CX1QjFcMIn1ZrsMpDD5h5S/SmoXBIxiiDcCEhS0O9pwxUjEgnUcx+qxSigDvS+mKNfZzO0otUKjsNG7aJAlNTa05llrCw8dphG5uSW8WoIULu8oZqt4m2mhAG6SSJdCHi3+4IAOLBLAAX8vG9OeFDgG4emU9IYxRWmgefYRZO16IOIqEKWmw9x0rpryqZLcPteiWdz6A4DXPvjI6QDr1Qt1AgIufvtkjXAuffhRVk/u+WM+rxhGdyeWCpC4/zRk99UKaL/6CKtWIu9x1KzmsRH2q+wjrUMi9z5saWws2rpEjsOj48HSjV4GhMq5aJ9APngXxuT53AY3Z8gdga1Ffcf8so6fVAT21dDybZZwROa+Shq2cnvggAMOeIlgZWo8UhbPCwblSA45Yv7B2JS5FfLRPx7YI7a/RVixH+JCV8RBkneZOJIZCcmcc9zD53elhNQardqQDTwvzd2V/6sPcP4FNpeJ27MiAhrEOro3xtYdRxN5BhbOMfXiTR3YGhpI3QYiYMlnTcbNpLkaRpifwI6jQzCzhGsqgHRD5HnCDYI=
        on:
          tags: true
    - stage: deploy
      if: type = push AND tag IS present
      name: Deploy to GitHub Pages
      node_js: lts/*
      script:
        - yarn dev
        - yarn --cwd ./demo build
        - echo "Deploying to GitHub pages..."
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: demo/build
        github_token: $GITHUB_TOKEN
        on:
          tags: true
